# Configuration for Label Actions - https://github.com/dessant/label-actions
"Needs: Issue Template":
  comment: >
    :wave: @{issue-author}, have a look at our issue template and make sure that you've filled out the required fields.
  # Close the issue
  close: true
"question":
  comment: >
    :thinking: @{issue-author}, this appears to be a question rather than an issue<br>please use GitHub Discussions or [Slack](https://slack.openstreetmap.us/).
  # Close the issue
  close: true
"stale":
  comment: >
    :thinking: @{issue-author} we're closing this issue due to lack of activity.
  # Close the issue
  close: true
